language: android
sudo: required
jdk: oraclejdk8
dist: trusty

env:
 global:
   - ANDROID_API=28
   - EMULATOR_API=26
   - ANDROID_BUILD_TOOLS_VERSION=28.0.3
   - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    - sys-img-armeabi-v7a-google_apis-28
    - sys-img-armeabi-v7a-google_apis-26
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - echo no | android create avd --force -n test -t android-26 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build check
